apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
        - env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: ' TRACE'
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          name: api-gateway-app
          image: renosbardis/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway-svc
  name: api-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: "TCP"
  selector:
    app: api-gateway-app
status:
  loadBalancer: {}