apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-app
  labels:
    app: customer-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : customer-service-app
  template:
    metadata:
      labels:
        app: customer-service-app
    spec:
      containers:
        - name: customer-service-app
          image: renosbardis/customer-service:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083

---

kind: Service
apiVersion: v1
metadata:
  name:  customer-service-svc
spec:
  selector:
    app:  customer-service-app
  ports:
    - port:  80
      targetPort:  8083