apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-service-cm
data:
  eureka_service_address: http://eureka-0.eureka:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: discovery-service
  selector:
    app: discovery-service

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discovery-service
spec:
  serviceName: "discovery-service"
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
        - name: discovery-service
          image: renosbardis/discovery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          resources: {}
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: discovery-service-cm
                  key: eureka_service_address


---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-lb
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service
#  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
status:
  loadBalancer: {}