apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-app
  labels:
    app: notification-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : notification-service-app
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          name: notification-service-app
          resources: {}
          image: renosbardis/notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name:  notification-service-svc
spec:
  selector:
    app:  notification-service-app
  ports:
    - port:  80
      targetPort:  8085
status:
  loadBalancer: {}