apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-app
  labels:
    app: transaction-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : transaction-service-app
  strategy: {}
  template:
    metadata:
      labels:
        app: transaction-service-app
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          name: transaction-service-app
          resources: {}
          image: renosbardis/transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name:  transaction-service-svc
spec:
  selector:
    app:  transaction-service-app
  ports:
    - port:  80
      targetPort:  8084
status:
  loadBalancer: {}